apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis.yaml
  - redis-sentinel.yaml
  - kafka.yaml
  - kafka-topics-job.yaml
  - postgres.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: distributed-trading
      app.kubernetes.io/managed-by: argocd
