apiVersion: batch/v1
kind: Job
metadata:
  name: trading-kafka-topics
spec:
  template:
    spec:
      containers:
        - name: create-topics
          env:
            - name: REPLICATION_FACTOR
              value: "3"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  template:
    spec:
      containers:
        - name: kafka
          env:
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 0@kafka-0.kafka:9093,1@kafka-1.kafka:9093,2@kafka-2.kafka:9093
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "2"
