apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - namespace.yaml
  - ../../base
labels:
  - pairs:
      platform.example.com/environment: dev
patches:
  - path: data-endpoints-patch.yaml
