apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - namespace.yaml
  - ../../base
labels:
  - pairs:
      platform.example.com/environment: staging
replicas:
  - name: trading-api
    count: 2
  - name: trading-worker
    count: 2
  - name: frontend
    count: 2
patches:
  - path: data-endpoints-patch.yaml
